Add `sched_priority` and `logbanner` options.
voxpupuli/puppet-chrony pull request #148
Opened 2022-04-15 14:41 UTC by jcpunk

#### Pull Request (PR) description
This patch adds a way to set the chrony options `sched_priority` and `logbanner`.

#### This Pull Request (PR) fixes the following issues
None

2022-04-15 15:04 UTC, root-expert requested changes
Thanks for the PR!

Please add basic unit tests for the new parameters.

2022-04-15 15:04 UTC, root-expert commented on manifests/init.pp
> +  Optional[Integer] $logbanner                                     = undef,
`logbanner` can't have negative values.
```suggestion
  Optional[Integer[0]] $logbanner                                  = undef,
```

2022-04-15 15:04 UTC, root-expert commented on manifests/init.pp
> +  Optional[Integer] $sched_priority                                = undef,
Same here. Probably there's an upper bound as well? 100 maybe?
```suggestion
  Optional[Integer[0]] $sched_priority                             = undef,
```

2022-04-15 15:41 UTC, jcpunk commented
I've taken a stab at fixing the things you noted.  This look better?

2022-04-15 18:52 UTC, root-expert approved these changes

2022-04-19 05:18 UTC, smortex approved these changes

2022-04-19 11:52 UTC, merged